# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.8.12

    working_directory: ~/Spectacles

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements-dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install non-python dependencies
          command: |
            sudo apt-get update
            sudo apt-get install libyaml-dev

      - run:
          name: install spectacles
          command: |
            python3 -m venv venv --clear
            . venv/bin/activate
            pip install -U pip
            pip install -r requirements-dev.txt
            pip install .

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements-dev.txt" }}

      - run:
          name: Check for secrets in cassettes
          command: scripts/detect_cassette_secrets.bash tests/cassettes/**/*.yaml

      - run:
          name: mypy
          command: |
            . venv/bin/activate
            mypy spectacles tests

      - run:
          name: flake8
          command: |
            . venv/bin/activate
            flake8 spectacles tests

      - run:
          name: black
          command: |
            . venv/bin/activate
            black --check spectacles tests

      - run:
          name: bandit
          command: |
            . venv/bin/activate
            bandit -r spectacles

      - run:
          name: pytest and coverage
          command: |
            . venv/bin/activate
            coverage run --source spectacles -m pytest
            coverage report

workflows:
  version: 2
  test:
    jobs:
      - test
